[package]
name = "saftladen"
version = "0.1.0"
edition = "2021"

[dependencies]
async-i3ipc = "0.7.0"
async-trait = "0.1.68"
chrono = "0.4.26"
futures = "0.3.28"
log = "0.4.19"
regex = "1.8.4"
simple_logger = "4.2.0"
tokio = { version = "1.28.2", features = ["full"] }
